version: "3"

services:
  nginx:
    container_name: nginx
    networks:
      - d102-network
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /home/ubuntu/nginx/conf.d:/etc/nginx/conf.d
      - /home/ubuntu/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /home/jenkins/var/jenkins_home/workspace/frontend/frontend/dist:/usr/share/nginx/html

networks:
  d102-network:
    name: d102-network
    external: true