version: "3"

name: d102-backend

services:
  mariadb:
    image: mariadb:10.11.7
    container_name: backend-mariadb
    restart: unless-stopped
    networks:
      - d102-network
    ports:
      - ${MARIADB_EXTERNAL_PORT}:${MARIADB_PORT}
    volumes:
      - ${HOME}/d102/mariadb/var/lib/mysql:/var/lib/mysql
    environment:
      TZ: "Asia/Seoul"
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    command: --character-set-server=utf8mb4  --collation-server=utf8mb4_bin
    
  redis:
    image: redis:7.2
    container_name: backend-redis
    restart: unless-stopped
    networks:
      - d102-network
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      TZ: "Asia/Seoul"
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 512M  
    
  backend-api:
    container_name: backend-api
    networks:
      - d102-network
    ports:
      - "8081:8081"
    image: ${REGISTRY}/backend-api:${TAG}
    volumes:
      - ${HOME}/d102/backend/api/logs:/app/logs
      - ${HOME}/d102/files:/files
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      TZ: "Asia/Seoul"
    restart: unless-stopped  
    
  backend-file:
    container_name: backend-file
    networks:
      - d102-network
    ports:
      - "8082:8082"
    image: ${REGISTRY}/backend-file:${TAG}
    volumes:
      - ${HOME}/d102/backend/file/logs:/app/logs
      - ${HOME}/d102/files:/files
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      TZ: "Asia/Seoul"
    restart: unless-stopped  

networks:
  d102-network:
    name: d102-network
    external: true