version: "3"

name: d102-backend

services:
  mariadb:
    image: mariadb:10.11.7
    container_name: backend-mariadb
    restart: unless-stopped
    ports:
      - ${MARIADB_EXTERNAL_PORT}:${MARIADB_PORT}
    volumes:
      - ${HOME}/d102/mariadb/var/lib/mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    command: --character-set-server=utf8mb4  --collation-server=utf8mb4_bin
    
  redis:
    image: redis:7.2
    container_name: backend-redis
    restart: unless-stopped
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    deploy:
      resources:
        limits:
          memory: 512M
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 512M  
    
  backend-api:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: backend-api
    ports:
      - ${API_EXTERNAL_PORT}:${API_PORT}
    image: ${REGISTRY}/backend-api:${TAG}
    volumes:
      - ${HOME}/d102/backend/api/logs:/app/logs
      - ${HOME}/d102/files:/files
    restart: unless-stopped  
    
  backend-file:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: backend-file
    ports:
      - ${FILE_EXTERNAL_PORT}:${FILE_PORT}
    image: ${REGISTRY}/backend-file:${TAG}
    volumes:
      - ${HOME}/d102/backend/file/logs:/app/logs
      - ${HOME}/d102/files:/files
    restart: unless-stopped  