server:
  port: 8082
  servlet:
    context-path: /file

spring:
  # DB Connection Info
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/d102
    username: danbi
    password: 1234

  # Jpa Setting
  jpa:
    hibernate:
      ddl-auto: none # none, create, update, create-drop
    defer-datasource-initialization: true
    properties:
      format_sql: true
    show-sql: false
    open-in-view: true

  # Redis Connection Info
  redis:
    host: localhost
    port: 6379
    password: 1234

  # MultiPart File Upload
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# Swagger
springdoc:
  packages-to-scan: com.d102.file.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    info:
      title: D102 FILE Server
      description: Sweet rain fell in class 4
      version: 0.0.1
  override-with-generic-response: false
  use-fqn: true

# logging
#logging:
#  level:
#    root: INFO
#    web: INFO
#    com.d102.file: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web.cors: DEBUG
#    org.hibernate.sql: DEBUG
#    org.hibernate.type.descriptor.sql: trace
logging:
  level:
    root: trace
    web: trace
    com.d102.file: trace
    org.springframework.security: trace
    org.springframework.web.cors: trace
    org.hibernate.sql: trace
    org.hibernate.type.descriptor.sql: trace

cors:
  origins: >
    http://localhost:5173    

jwt:
  access-token-key: 40/22SrNuOvYU5HcMI/KVYCfdjn9Au2Rav345b1vf45b1xws
  refresh-token-key: ZuLXKJgsW29iW2uB5V9xxh0QW8Xihxdm0VP31zginC412xc431c
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800

download:
  profile:
    base-url: http://localhost:8082/file/download/profile?path=

open-ai:
  url: https://api.openai.com/v1/chat/completions
  secret-key: secret

fast-ai:
  url: http://localhost:8000/ai/analysis/
