server:
  port: 8081
  servlet:
    context-path: /api

spring:
  # DB Connection Info
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/d102
    username: danbi
    password: 1234

  # Jpa Setting
  jpa:
    hibernate:
      ddl-auto: none # none, create, update, create-drop
    defer-datasource-initialization: true
    properties:
      format_sql: true
    show-sql: false
    open-in-view: true

  # Redis Connection Info
  redis:
    host: localhost
    port: 6379
    password: 1234

  # SMTP Info
  mail:
    host: smtp.gmail.com
    port: 587
    username: secret
    password: secret
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

# Swagger
springdoc:
  packages-to-scan: com.d102.api.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    info:
      title: D102 API Server
      description: Sweet rain fell in class 4
      version: 0.0.1

# logging
logging:
  level:
    root: INFO
    web: DEBUG
    com.d102.api: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql: trace

cors:
  origins: >
    http://localhost:5173



