version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: unless-stopped
    ports:
      - $FASTAPI_PORT:8000
    env_file:
      - .env
    command: "/app/wait-for-it.sh $DB_HOST:$DB_PORT -t 10 -- poetry run uvicorn main:app --reload --host=0.0.0.0"
